"""tambah_nama_ilmiah_dan_referensi_di_kategori

Revision ID: 2cc9c2ec9d58
Revises: 905ae0bc78f6
Create Date: 2026-06-25 12:35:16.431653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc9c2ec9d58'
down_revision: Union[str, Sequence[str], None] = '905ae0bc78f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kategori_klasifikasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_ilmiah', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('referensi', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kategori_klasifikasi', schema=None) as batch_op:
        batch_op.drop_column('referensi')
        batch_op.drop_column('nama_ilmiah')

    # ### end Alembic commands ###
